version: '2.1'
services:
    afpostgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    afwebserver:
        image: puckel/docker-airflow:latest
        restart: always
        depends_on:
            - afpostgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - oramirez@lt336912/home/oramirez/projects/airflow/test_esbi/app/dags:/usr/local/airflow/dags
            - oramirez@lt336912/home/oramirez/projects/airflow/test_esbi/app/requirements.txt:/requirements.txt
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
